# Generated by Django 3.0.4 on 2020-08-29 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToDo',
            new_name='ToDoApp',
        ),
    ]
